# Generated by Django 5.2.8 on 2025-12-02 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('grupo_muscular', models.CharField(blank=True, max_length=60, null=True)),
                ('equipamento', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'exercicios',
            },
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidade', models.CharField(choices=[('corrida', 'Corrida'), ('ciclismo', 'Ciclismo'), ('musculacao', 'Musculação')], max_length=20)),
                ('inicio_em', models.DateTimeField()),
                ('duracao_seg', models.IntegerField(blank=True, null=True)),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sessoes_atividade',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hash_senha', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='MetricasCiclismo',
            fields=[
                ('sessao', models.OneToOneField(db_column='sessao_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metricas_ciclismo', serialize=False, to='core.sessaoatividade')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('velocidade_media_kmh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fc_media', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metricas_ciclismo',
            },
        ),
        migrations.CreateModel(
            name='MetricasCorrida',
            fields=[
                ('sessao', models.OneToOneField(db_column='sessao_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metricas_corrida', serialize=False, to='core.sessaoatividade')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ritmo_medio_seg_km', models.IntegerField()),
                ('fc_media', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metricas_corrida',
            },
        ),
        migrations.AddField(
            model_name='sessaoatividade',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='MetaHabito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('modalidade', models.CharField(choices=[('corrida', 'Corrida'), ('ciclismo', 'Ciclismo'), ('musculacao', 'Musculação')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('frequencia_semana', models.SmallIntegerField(blank=True, null=True)),
                ('distancia_meta_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duracao_meta_min', models.IntegerField(blank=True, null=True)),
                ('sessoes_meta', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.usuario')),
            ],
            options={
                'db_table': 'metas_habito',
            },
        ),
        migrations.CreateModel(
            name='MarcacaoHabito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('concluido', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(db_column='meta_id', on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes', to='core.metahabito')),
                ('sessao', models.ForeignKey(blank=True, db_column='sessao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes', to='core.sessaoatividade')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes', to='core.usuario')),
            ],
            options={
                'db_table': 'marcacoes_habito',
            },
        ),
        migrations.CreateModel(
            name='SerieMusculacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordem_serie', models.IntegerField()),
                ('repeticoes', models.IntegerField(blank=True, null=True)),
                ('carga_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('exercicio', models.ForeignKey(db_column='exercicio_id', on_delete=django.db.models.deletion.PROTECT, related_name='series', to='core.exercicio')),
                ('sessao', models.ForeignKey(db_column='sessao_id', on_delete=django.db.models.deletion.CASCADE, related_name='series_musculacao', to='core.sessaoatividade')),
            ],
            options={
                'db_table': 'series_musculacao',
                'indexes': [models.Index(fields=['sessao'], name='idx_series_sessao'), models.Index(fields=['exercicio'], name='idx_series_exercicio')],
            },
        ),
        migrations.AddIndex(
            model_name='sessaoatividade',
            index=models.Index(fields=['usuario', '-inicio_em'], name='idx_sessoes_usuario_tempo'),
        ),
        migrations.AddIndex(
            model_name='sessaoatividade',
            index=models.Index(fields=['modalidade'], name='idx_sessoes_modalidade'),
        ),
        migrations.AlterUniqueTogether(
            name='marcacaohabito',
            unique_together={('meta', 'data')},
        ),
    ]
